In [126]:
from tensorflow import keras
from keras.preprocessing.image import load_img, img_to_array
import cv2
import numpy as np

In [36]:
model = keras.models.load_model('coffee.h5')

In [ ]:
model.predict_classes()

In [148]:
def make_prediction(file_path, model):
    image = cv2.imread(file_path)
    image = cv2.resize(image, (224,224))
    image = image * 1.0
    image = np.reshape(image,[1, 224, 224, 3])
    prediction = model.predict_classes(image, batch_size=1)
    print(model.predict(image))
    return prediction, image

In [141]:
def tf_image_load(file_path, model):
    image = load_img(file_path, target_size=(224, 224))
    x = img_to_array(image)
    x = np.expand_dims(x, axis=0)
    images = np.vstack([x])
    pred_classes = model.predict(images, batch_size=10)
    classes = pred_classes.argmax(axis=-1)
    return classes[0]

In [142]:
im = tf_image_load('/Users/flatironschool/Downloads/test/rust/rust3.jpg', model)

In [144]:
im

2

In [133]:
classes = pred_classes.argmax(axis=-1)
classes[0]

2

In [11]:
import glob

In [145]:
for im in glob.glob(
    '/Users/flatironschool/Documents/school/inclass/projects/final_project/crop_alert/data_processing/data/test/red_spider_mite/*'):
    pred = tf_image_load(im, model)
    if pred ==1:
        print(im.split('/')[-1], pred)

Labeled_Data_304.jpg 1
Labeled_Data_191.jpg 1
Labeled_Data_257.jpg 1
Labeled_Data_122.jpg 1


In [150]:
make_prediction('/Users/flatironschool/Downloads/test/rust/rust2.jpg', model)

[[1. 0. 0.]]


(array([0]), array([[[[ 66.,  74.,  73.],
          [ 63.,  71.,  70.],
          [ 59.,  68.,  65.],
          ...,
          [ 18.,  29.,  21.],
          [ 19.,  30.,  22.],
          [ 20.,  31.,  23.]],
 
         [[ 67.,  74.,  74.],
          [ 63.,  71.,  70.],
          [ 61.,  69.,  67.],
          ...,
          [ 20.,  31.,  21.],
          [ 21.,  32.,  21.],
          [ 23.,  33.,  24.]],
 
         [[ 68.,  76.,  75.],
          [ 64.,  73.,  71.],
          [ 62.,  71.,  68.],
          ...,
          [ 22.,  33.,  23.],
          [ 23.,  34.,  24.],
          [ 25.,  36.,  26.]],
 
         ...,
 
         [[ 18.,  37.,  45.],
          [ 19.,  38.,  46.],
          [ 20.,  39.,  47.],
          ...,
          [114., 115., 171.],
          [117., 116., 176.],
          [129., 124., 183.]],
 
         [[ 20.,  39.,  47.],
          [ 20.,  39.,  47.],
          [ 22.,  41.,  49.],
          ...,
          [120., 123., 176.],
          [113., 113., 173.],
          [125.

In [3]:
from coffee_prediction import make_prediction

In [61]:
make_prediction('rust.jpg', model)

[[0.2906851  0.21739453 0.49192038]]


2

In [ ]:
from keras import 

In [92]:
test_datagen = keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

test_validation_generator = test_datagen.flow_from_directory(
    '/Users/flatironschool/Downloads/test/',
        #'/Users/flatironschool/Documents/school/inclass/projects/final_project/crop_alert/data_processing/data/test/',
        target_size=(224,224),
        batch_size=16,
        class_mode='categorical',
        shuffle=False)

Found 6 images belonging to 3 classes.


In [93]:
p = next(test_validation_generator)
p

(array([[[[0.3921569 , 0.5411765 , 0.48235297],
          [0.40000004, 0.56078434, 0.5058824 ],
          [0.38431376, 0.54509807, 0.4901961 ],
          ...,
          [0.4431373 , 0.43921572, 0.42352945],
          [0.5411765 , 0.627451  , 0.33333334],
          [0.5568628 , 0.67058825, 0.30980393]],
 
         [[0.3921569 , 0.5411765 , 0.4901961 ],
          [0.38823533, 0.54901963, 0.49411768],
          [0.3803922 , 0.5294118 , 0.4784314 ],
          ...,
          [0.53333336, 0.5372549 , 0.5137255 ],
          [0.5372549 , 0.627451  , 0.27450982],
          [0.54509807, 0.6313726 , 0.3372549 ]],
 
         [[0.36862746, 0.5294118 , 0.47450984],
          [0.3529412 , 0.5137255 , 0.45882356],
          [0.37647063, 0.5254902 , 0.47450984],
          ...,
          [0.54901963, 0.5647059 , 0.50980395],
          [0.5254902 , 0.61960787, 0.23529413],
          [0.5372549 , 0.6039216 , 0.3254902 ]],
 
         ...,
 
         [[0.5019608 , 0.42352945, 0.38823533],
          [0.48235

In [97]:
p[0][0].shape

(224, 224, 3)

In [99]:
p[1][0]

array([1., 0., 0.], dtype=float32)

In [87]:
test_validation_generator.classes

array([0, 1, 2, 2, 2, 2], dtype=int32)

In [83]:
y_pred = model.predict_generator(test_validation_generator)
y_pred = y_pred.argmax(axis=1)

In [84]:
y_pred

array([0, 2, 2, 2, 1, 2])

In [85]:
from sklearn.metrics import confusion_matrix, classification_report

In [86]:
class_names = np.array(list(test_validation_generator.class_indices.keys()))
print(classification_report(test_validation_generator.classes, y_pred, target_names=class_names))

                 precision    recall  f1-score   support

        healthy       1.00      1.00      1.00         1
red_spider_mite       0.00      0.00      0.00         1
           rust       0.75      0.75      0.75         4

       accuracy                           0.67         6
      macro avg       0.58      0.58      0.58         6
   weighted avg       0.67      0.67      0.67         6



In [88]:
import pandas as pd

In [89]:
# Compute confusion matrix
cm = confusion_matrix(test_validation_generator.classes, y_pred)

In [90]:
cm_df =  pd.DataFrame(cm, columns=class_names, index=class_names)

In [91]:
cm_df

healthy  red_spider_mite  rust
healthy                1                0     0
red_spider_mite        0                0     1
rust                   0                1     3